# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('sever_group_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('changer_account', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'service_server_group',
            },
        ),
        migrations.CreateModel(
            name='ServiceServer',
            fields=[
                ('server_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('host_name', models.CharField(blank=True, max_length=20)),
                ('public_ip', models.GenericIPAddressField(protocol=b'IPv4')),
                ('private_ip', models.GenericIPAddressField(protocol=b'IPv4')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('changer_account', models.CharField(blank=True, max_length=20)),
                ('sever_group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.ServerGroup')),
            ],
            options={
                'db_table': 'service_server',
            },
        ),
    ]
